#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform image2D inputImage;
layout (binding = 1, rgba8) uniform image2D resultImage;

void main() 
{
    vec4 rgba = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)).rgba;
    float grey = rgba.r*0.299+rgba.g*0.587+rgba.b*0.114;
    vec4 col = vec4(grey, grey, grey, rgba.a);
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), col);
}